name: "demo workflow/pipeline"

on:
  push: # Event: triggers whenever there is a push made to the repository on test branch
    branches:
      - test
  
  pull_request: # Event: triggers whenever there is a pull request made to the repository on main branch
    branches:
      - main
    
    types:
      - closed  # only trigger when PR is closed

  workflow_dispatch:  # manual trigger

jobs:
  on-demo-push: # Job 1 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: "Run on test branch push event"
        run: echo "This job runs on push event to test branch."

  on-demo-pr: # Job 2
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: "Run on pull request to main branch"
        run: echo "This job runs on pull request event to main branch."

  on-workflow-dispatch: # Job 3
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: "Run on manual workflow dispatch"
        run: echo "This job runs on manual workflow dispatch event."

  on-pr-closed: # Job 4
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: "Run on pull request closed"
        run: echo "This job runs when a pull request to main branch is closed."